oracle_client = r"C:\Program Files (x86)\Oracle\instantclient_21_12"

oracle_schemas = ["'PO'", "'AP'"]

db_schema_sql = f"""SELECT CONCAT(at.OWNER, CONCAT('.', at.TABLE_NAME)) AS "tab"
, c.COLUMN_NAME AS "col" -- USER_COLUMN_NAME
, c.COLUMN_TYPE AS "datatype" -- D = date, N = number, V = varchar, I = rowid, L = long, X = long raw
, c.DESCRIPTION AS "col_desc" --for testing
, at.NUM_ROWS AS "num_rows"
, t.DESCRIPTION AS "tab_desc"
FROM sys.ALL_TABLES at
LEFT JOIN APPLSYS.FND_TABLES t ON t.TABLE_NAME = at.TABLE_NAME AND t.ZD_EDITION_NAME = 'SET2'
LEFT OUTER JOIN APPLSYS.FND_COLUMNS c ON c.TABLE_ID = t.TABLE_ID AND c.ZD_EDITION_NAME = 'SET2'
WHERE at.OWNER IN ({', '.join(oracle_schemas)})
ORDER BY at.OWNER, at.TABLE_NAME, c.COLUMN_ID
"""
db_pks_sql = f"""SELECT CONCAT(at.OWNER, CONCAT('.', at.TABLE_NAME)) AS "tab",
c.COLUMN_NAME AS "col",
pk.PRIMARY_KEY_ID AS "pk_id",
pk.PRIMARY_KEY_NAME AS "pk_name"
FROM sys.ALL_TABLES at
LEFT JOIN APPLSYS.FND_TABLES t ON t.TABLE_NAME = at.TABLE_NAME AND t.ZD_EDITION_NAME = 'SET2'
LEFT JOIN APPLSYS.FND_PRIMARY_KEYS pk ON pk.TABLE_ID = t.TABLE_ID AND pk.ZD_EDITION_NAME = 'SET2'
LEFT JOIN APPLSYS.FND_PRIMARY_KEY_COLUMNS pkc on pkc.PRIMARY_KEY_ID = pk.PRIMARY_KEY_ID AND pkc.ZD_EDITION_NAME = 'SET2'
LEFT JOIN APPLSYS.FND_COLUMNS c ON c.COLUMN_ID = pkc.COLUMN_ID AND c.ZD_EDITION_NAME = 'SET2'
WHERE at.OWNER IN ({', '.join(oracle_schemas)})
ORDER BY at.OWNER, at.TABLE_NAME, c.COLUMN_ID, pk.PRIMARY_KEY_ID, PRIMARY_KEY_SEQUENCE
"""
# foreign key ids may not be <= 0
db_fks_sql = f"""SELECT CONCAT(at.OWNER, CONCAT('.', at.TABLE_NAME)) AS "tab",
c.COLUMN_NAME AS "col",
fk.FOREIGN_KEY_ID AS "fk_id",
fk.FOREIGN_KEY_NAME AS "fk_name",
fk.PRIMARY_KEY_ID AS "fk_target_id"
FROM sys.ALL_TABLES at
LEFT JOIN APPLSYS.FND_TABLES t ON t.TABLE_NAME = at.TABLE_NAME AND t.ZD_EDITION_NAME = 'SET2'
LEFT JOIN APPLSYS.FND_FOREIGN_KEYS fk ON fk.TABLE_ID = t.TABLE_ID AND fk.ZD_EDITION_NAME = 'SET2'
LEFT JOIN APPLSYS.FND_FOREIGN_KEY_COLUMNS fkc on fkc.FOREIGN_KEY_ID = fk.FOREIGN_KEY_ID AND fkc.ZD_EDITION_NAME = 'SET2'
LEFT JOIN APPLSYS.FND_COLUMNS c ON c.COLUMN_ID = fkc.COLUMN_ID AND c.ZD_EDITION_NAME = 'SET2'
WHERE at.OWNER IN ({', '.join(oracle_schemas)})
ORDER BY at.OWNER, at.TABLE_NAME, c.COLUMN_ID, fk.FOREIGN_KEY_ID, fkc.FOREIGN_KEY_SEQUENCE
"""
